### PR TITLE
Vm shutdown

### PR DESCRIPTION
**Pull request by sharma20**

### CODE REVIEW

**Review by richiedjohnson — CHANGES_REQUESTED** [review]
monitor_XenVM
============
+ create a function listenToVMShutdown(dom_id, user_id) and call this function from start() in VirtualMachine
+ watch for the exact string rather than a random string
+ you might not have to pass api_key [[ Not sure - have to run and check ]]

xen_api
======
+ from VirtualMachine class start() function - call listenToVMShutdown(dom_id, user_id) rather than calling the py file through cmd. Calls through cmd will slower and against OOPs :) - so avoid when possible

pyxs
===
+ good one. I did not use this when I had to get vnc port. You should definitely use this same library there as well

**Comment by theryecatcher** [comment]
### monitor_xenVM & xen_api

1. Could be done as a function but we need to run the monitor service in the background for multiple VM's at the same time as a daemon. I explored involving threading in the code and making each thread (a function call) a daemon but wasn't sure of the performance and feasibility so had to take the easy way out. Would you suggest that we go ahead and use threads?

2. Will see if we can figure out the exact string. As xl clears all the domains and properties on shutdown there was no way we could have the exact string and there is little to no documentation on that behavior while it still does get triggered on any random string, will see if we can figure out the exact values.

### pyxs

Yes we should be able to replace all places where xl or xenstore is invoked. Will work on that.

**Comment by theryecatcher** [comment]
@richiedjohnson Richie could you please check the changes and let me know if we need to have any further modifications.

- The Monitoring has been implemented as a part of xen-api itself but as [threads](https://github.com/vital2/xen-api/pull/2/commits/f6eab1f5d8a901fcadd581e8527baaebdbad79f9).

- The whole http post request for the update of status to web server has been [replaced](d0cf7fad8c04b7fa17fd6cf816800bdf146b46a6) by a [ZMQ](https://github.com/zeromq/pyzmq) solution with a PUSH PULL pattern. Now a server runs on the local network through which the communication is enabled thus reducing latency and also enabling parallel acknowledgements based on the number of slave (pull) workers.

**Comment by theryecatcher** [comment]
Closed stale Pull Request.

**Pull request closed without merging**
